name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      - name: Install Haxelib
        run: |  
          haxelib setup ~/haxelib
          haxelib install flixel
          haxelib install lime
          haxelib install hxcpp
          haxelib git hxflac https://github.com/GreenColdTea/justAthing.git
          haxelib run lime setup flixel
          haxelib list
      - name: Compile Test Project Linux
        run: haxelib run lime build ${{ github.workspace }}/test/Project.xml linux
      - name: Publish Linux Artifact
        uses: actions/upload-artifact@main
        with:
          name: linuxBuild
          path: ${{ github.workspace }}/test/export/release/linux/bin

  buildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install flixel
          haxelib install lime
          haxelib install hxcpp
          haxelib git hxflac https://github.com/GreenColdTea/justAthing.git
          haxelib run lime setup flixel
          haxelib list
      - name: Compile Test Project Windows
        run: haxelib run lime build ${{ github.workspace }}/test/Project.xml windows
      - name: Publish Windows Artifact
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: ${{ github.workspace }}/test/export/release/windows/bin

  buildMac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install flixel
          haxelib install lime
          haxelib install hxcpp
          haxelib git hxflac https://github.com/GreenColdTea/justAthing.git
          haxelib run lime setup flixel
          haxelib list
      - name: Compile Test Project Mac
        run: haxelib run lime build ${{ github.workspace }}/test/Project.xml mac
      - name: Publish Mac Artifact
        uses: actions/upload-artifact@main
        with:
          name: macBuild
          path: ${{ github.workspace }}/test/export/release/macos/bin

  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      - name: Install Android SDK and setup environment
        uses: android-actions/setup-android@v2
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install flixel
          haxelib install lime
          haxelib install hxcpp
          haxelib install lime
          haxelib git hxflac https://github.com/GreenColdTea/justAthing.git
          haxelib run lime setup android
          haxelib list
      - name: Compile Test Project Android
        run: haxelib run lime build ${{ github.workspace }}/test/Project.xml android
      - name: Publish Android Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: ${{ github.workspace }}/test/export/release/android/bin

  buildIOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install flixel
          haxelib install lime
          haxelib install hxcpp
          haxelib git hxflac https://github.com/GreenColdTea/justAthing.git
          haxelib run lime setup ios
          haxelib list
      - name: Compile Test Project iOS
        run: haxelib run lime build ${{ github.workspace }}/test/Project.xml ios
      - name: Publish iOS Artifact
        uses: actions/upload-artifact@main
        with:
          name: iosBuild
          path: ${{ github.workspace }}/test/export/release/ios/bin